### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by frisitano** [scroll-tech/reth#16]
# Milestone 1 Tracking Issue

The objective of Milestone 1 is to be able to feed blocks to reth via the engine API and verify that the blocks are valid.

# Issues

- [x] https://github.com/scroll-tech/reth/issues/24
- [x] https://github.com/scroll-tech/reth/issues/4
- [x] https://github.com/scroll-tech/reth/issues/40
- [x] https://github.com/scroll-tech/reth/issues/7
- [x] https://github.com/scroll-tech/reth/issues/5
- [x] https://github.com/scroll-tech/reth/issues/12
- [x] https://github.com/scroll-tech/reth/issues/38
- [x] https://github.com/scroll-tech/reth/issues/37
- [x] https://github.com/scroll-tech/reth/issues/35
- [x] https://github.com/scroll-tech/reth/issues/69

**Comment by frisitano** [comment]
Milestone 1 has been completed.
