### ISSUE TITLE
Milestone 4 Tracking Issue

### ISSUE THREAD

**Issue by frisitano** [scroll-tech/reth#92]
### Describe the feature

- [x] scroll-tech/reth#91 
- [x] scroll-tech/reth#61
- [x] scroll-tech/reth#59
- [x] scroll-tech/reth#58
- [x] scroll-tech/reth#57 
- [x] https://github.com/scroll-tech/rollup-node/issues/55
